//! Cross-cutting tests: polymorphic trait, SIMD consistency, artifact manifest.

use crate::helpers;

#[test]
#[ignore]
fn polymorphic_trait_both_devices() {
    let mut rtl = helpers::open_rtlsdr().expect("open RTL-SDR");
    let mut airspy = helpers::open_airspy().expect("open Airspy");
    // Both behind Box<dyn SdrDevice>; set frequency on each through the trait.
    rtl.set_frequency(100_000_000)
        .expect("RTL-SDR set_frequency");
    airspy
        .set_frequency(100_000_000)
        .expect("Airspy set_frequency");
    println!("both devices set_frequency via Box<dyn SdrDevice> OK");
}

#[test]
#[ignore]
fn simd_matches_independent_scalar_reference() {
    // Include all byte values and an odd tail rather than comparing the SIMD
    // function with itself on a lane-aligned buffer.
    let test_cu8: Vec<u8> = (0..=u8::MAX).cycle().take(1027).collect();
    let mut actual = vec![0.0f32; test_cu8.len()];
    sdr_fox_simd::cu8_to_cf32(&test_cu8, &mut actual);
    for (index, (&byte, &actual)) in test_cu8.iter().zip(&actual).enumerate() {
        let expected = (f32::from(byte) - 127.5) / 127.5;
        assert!(
            actual.to_bits().abs_diff(expected.to_bits()) <= 1,
            "index {index}, byte {byte}: actual={actual}, expected={expected}"
        );
    }
    println!("SIMD consistency: OK");
}

#[test]
#[ignore]
fn artifact_manifest() {
    use std::path::Path;
    let artifacts = [
        "tests/artifacts/rtl_spectrogram_test.png",
        "tests/artifacts/rtl_wbfm_test.wav",
        "tests/artifacts/airspy_spectrogram_test.png",
        "tests/artifacts/airspy_wbfm_test.wav",
    ];
    let mut found = 0;
    for path in &artifacts {
        if Path::new(path).exists() {
            let size = std::fs::metadata(path).map(|m| m.len()).unwrap_or(0);
            assert!(size > 100, "{path} is too small ({size} bytes)");
            println!("  {path}: {size} bytes");
            found += 1;
        } else {
            println!("  {path}: (not generated by prior test)");
        }
    }
    println!(
        "artifact_manifest: {found}/{} artifacts present",
        artifacts.len()
    );
    assert!(found >= 1, "at least one artifact should exist");
}
