/*
 * sdr-fox C API — auto-generated by cbindgen. Do not edit.
 * Library: sdr-fox (https://github.com/SondeFox/sdr-fox)
 * License: MIT OR Apache-2.0
 */

#ifndef SDR_FOX_H
#define SDR_FOX_H

/* Generated with cbindgen:0.29.4 */

/* Warning: this file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque device handle.
 */
typedef struct SdrFoxDevice SdrFoxDevice;

/**
 * Opaque stream handle.
 *
 * RTL streams are pulled directly through the core timed-receive contract.
 * Airspy retains a bounded worker so IQ synthesis overlaps caller copying.
 * In both modes a partially read [`sdr_fox_core::IqBlock`] stays owned here;
 * no second spill allocation or suffix copy is made.
 */
typedef struct SdrFoxStream SdrFoxStream;

/**
 * Integer hardware-family selector accepted by [`sdrfox_open_index`].
 *
 * This deliberately is not a Rust/C enum: every `u32` bit pattern is valid at
 * the ABI boundary and is checked before conversion to the private Rust enum.
 */
typedef uint32_t SdrFoxKind;

/**
 * Integer sample-format selector accepted by [`sdrfox_start_stream`].
 *
 * Like [`SdrFoxKind`], this is an integer typedef rather than an enum so an
 * invalid value can be rejected inside the FFI boundary without first
 * creating an invalid Rust discriminant.
 */
typedef uint32_t SdrFoxFormat;

/**
 * Snapshot of metadata and copy progress for one C stream.
 */
typedef struct SdrFoxStreamStats {
  /**
   * Producer-reported cumulative dropped-sample count on the last block.
   */
  uint64_t last_dropped;
  /**
   * Producer sequence number of the last block accepted by this adapter.
   */
  uint64_t last_sequence;
  /**
   * Blocks accepted by the adapter, including a partially drained block.
   */
  uint64_t blocks_read;
  /**
   * Bytes copied into caller buffers across all successful reads.
   */
  uint64_t bytes_read;
} SdrFoxStreamStats;

/**
 * Auto-detect (RTL-SDR first, then Airspy).
 */
#define SDRFOX_KIND_AUTO 0

/**
 * RTL-SDR.
 */
#define SDRFOX_KIND_RTLSDR 1

/**
 * Airspy.
 */
#define SDRFOX_KIND_AIRSPY 2

/**
 * Legacy spelling of [`SDRFOX_KIND_AUTO`].
 */
#define SdrFoxKind_Auto SDRFOX_KIND_AUTO

/**
 * Legacy spelling of [`SDRFOX_KIND_RTLSDR`].
 */
#define SdrFoxKind_Rtlsdr SDRFOX_KIND_RTLSDR

/**
 * Legacy spelling of [`SDRFOX_KIND_AIRSPY`].
 */
#define SdrFoxKind_Airspy SDRFOX_KIND_AIRSPY

/**
 * Interleaved unsigned 8-bit IQ.
 */
#define SDRFOX_FORMAT_CU8 0

/**
 * Interleaved signed 8-bit IQ.
 */
#define SDRFOX_FORMAT_CS8 1

/**
 * Interleaved signed native-endian 16-bit IQ.
 */
#define SDRFOX_FORMAT_CS16 2

/**
 * Interleaved native-endian IEEE-754 single-precision IQ.
 */
#define SDRFOX_FORMAT_CF32 3

/**
 * Legacy spelling of [`SDRFOX_FORMAT_CU8`].
 */
#define SdrFoxFormat_Cu8 SDRFOX_FORMAT_CU8

/**
 * Legacy spelling of [`SDRFOX_FORMAT_CS8`].
 */
#define SdrFoxFormat_Cs8 SDRFOX_FORMAT_CS8

/**
 * Legacy spelling of [`SDRFOX_FORMAT_CS16`].
 */
#define SdrFoxFormat_Cs16 SDRFOX_FORMAT_CS16

/**
 * Legacy spelling of [`SDRFOX_FORMAT_CF32`].
 */
#define SdrFoxFormat_Cf32 SDRFOX_FORMAT_CF32

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open a device by index. On success, sets `*out` to a new handle and returns
 * null (no error). On failure, returns a pointer to a UTF-8 error string.
 * That error pointer remains valid until the next failed open on the calling
 * thread; copy it if it must be retained.
 *
 * `kind` is a `u32` corresponding to a [`SdrFoxKind`] discriminant; an
 * out-of-range value is rejected with an error string rather than invoking
 * undefined behavior.
 *
 * # Safety
 *
 * `out` must be a valid, non-null pointer to a `sdrfox_device*` slot.
 */
 const char *sdrfox_open_index(uintptr_t index, SdrFoxKind kind, struct SdrFoxDevice **out);

/**
 * Close a device handle. Idempotent; null, stale, and repeated handles are
 * no-ops. A call already in progress retains an [`Arc`] until it returns.
 *
 * # Safety
 *
 * `dev` must be a valid pointer returned by `sdrfox_open_*`, or null (no-op).
 */
 void sdrfox_close(struct SdrFoxDevice *dev);

/**
 * Set the center frequency in Hz. Returns 0 on success, -1 on error.
 *
 * # Safety
 *
 * `dev` must be a valid, non-null device handle.
 */
 int sdrfox_set_frequency(struct SdrFoxDevice *dev, uint64_t hz);

/**
 * Set the sample rate in Hz. Returns 0 on success, -1 on error.
 *
 * # Safety
 *
 * `dev` must be a valid, non-null device handle.
 */
 int sdrfox_set_sample_rate(struct SdrFoxDevice *dev, uint32_t hz);

/**
 * Enable/disable the bias tee. Returns 0 on success, -1 on error.
 */
 int sdrfox_set_bias_tee(struct SdrFoxDevice *dev, int on);

/**
 * Enable/disable AGC. Returns 0 on success, -1 on error.
 */
 int sdrfox_set_agc(struct SdrFoxDevice *dev, int on);

/**
 * Set the overall gain in tenths of dB. Returns 0 on success, -1 on error.
 */
 int sdrfox_set_gain(struct SdrFoxDevice *dev, int tenths_db);

/**
 * Set the frequency correction in PPM. Returns 0 on success, -1 on error.
 */
 int sdrfox_set_freq_correction(struct SdrFoxDevice *dev, double ppm);

/**
 * Enable the SpyVerter (120 MHz HF upconverter). Returns 0 on success, -1 on error.
 */
 int sdrfox_enable_spyverter(struct SdrFoxDevice *dev);

/**
 * Disable any upconverter. Returns 0 on success, -1 on error.
 */
 int sdrfox_disable_upconverter(struct SdrFoxDevice *dev);

/**
 * Start streaming. On success, sets `*out` to a new stream handle and returns 0.
 *
 * `format` is a `u32` corresponding to a [`SdrFoxFormat`] discriminant; an
 * out-of-range value is rejected with a non-zero return code before any device
 * state is touched.
 *
 * # Safety
 *
 * `dev` must be valid and non-null; `out` must be a valid pointer to a
 * `sdrfox_stream*` slot.
 */
 int sdrfox_start_stream(struct SdrFoxDevice *dev, SdrFoxFormat format, struct SdrFoxStream **out);

/**
 * Read up to `len` bytes from the stream into `buf`. Returns bytes read, 0 on
 * timeout/end-of-stream, or -1 on error.
 *
 * A positive `timeout_ms` bounds this call without cancelling the stream; a
 * later read can still receive the next block. Zero or a negative value blocks
 * until data, stop, end-of-stream, or error. Concurrent reads are serialized,
 * and the timeout includes any wait behind another reader.
 *
 * Any bytes that do not fit in `buf` (because a delivered block is larger than
 * `len`) remain in the stream handle's owned IQ block and are returned on the
 * next read, so short caller buffers neither discard nor duplicate data.
 *
 * All advertised formats are returned as contiguous native representations:
 * Cu8 and Cs8 as bytes, Cs16 as native-endian `i16` bytes, and Cf32 as
 * native-endian IEEE-754 `f32` bytes.
 *
 * # Safety
 *
 * `stream` must be valid and non-null; `buf` must point to at least `len`
 * writable bytes.
 */

intptr_t sdrfox_read_stream(struct SdrFoxStream *stream,
                            uint8_t *buf,
                            uintptr_t len,
                            int timeout_ms);

/**
 * Copy a coherent stream metadata snapshot into `out`. Returns 0 on success
 * and -1 for a null, stale, or invalid handle.
 *
 * # Safety
 *
 * `stream` must be a live stream token and `out` must point to writable
 * storage for one [`SdrFoxStreamStats`].
 */
 int sdrfox_stream_stats(struct SdrFoxStream *stream, struct SdrFoxStreamStats *out);

/**
 * Request stream stop without destroying the handle. Idempotent and safe to
 * call concurrently with [`sdrfox_read_stream`]. The handle remains valid
 * until [`sdrfox_close_stream`] is called.
 *
 * # Safety
 *
 * `stream` must be a valid pointer returned by `sdrfox_start_stream`, or null.
 */
 void sdrfox_stop_stream(struct SdrFoxStream *stream);

/**
 * Close a stream handle. Idempotent and safe to call concurrently with a
 * reader: removal prevents new calls while an in-flight call retains its own
 * [`Arc`]. Closing implicitly requests stop.
 *
 * # Safety
 *
 * `stream` may be a pointer returned by `sdrfox_start_stream`, a stale handle,
 * or null.
 */
 void sdrfox_close_stream(struct SdrFoxStream *stream);

/**
 * Retrieve the last error message for a device. Returns null if no error. The
 * message is copied into thread-local storage and remains valid until the next
 * FFI error-string operation on the calling thread (or thread exit).
 *
 * # Safety
 *
 * `dev` may be null (returns null).
 */
 const char *sdrfox_last_error(struct SdrFoxDevice *dev);

/**
 * Get the sdr-fox library version string (static, never freed).
 */
 const char *sdrfox_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SDR_FOX_H */
