[package]
name = "sdr-fox-rtlsdr"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "RTL2832U + multi-tuner (R820T2, E4000, FCxxxx) SDR driver for sdr-fox"
categories.workspace = true
keywords.workspace = true

[dependencies]
sdr-fox-core.workspace = true
sdr-fox-transport.workspace = true
sdr-fox-simd.workspace = true
crossbeam-channel.workspace = true
thiserror.workspace = true
tracing.workspace = true
